spring.application.name=CRUDDemo
spring.main.web-application-type=none
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_demo
spring.datasource.username=postgres
spring.datasource.password=

# Configuracion de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect